name: Heroku Deployment Pipeline

on:
  push:
    branches:
      - master
    pull_request:
      branches: [master]
      types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    if: ${{ github.event_name == 'push'}}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.9.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fierce-scrubland-23190"
          heroku_email: "mrlamchensian@gmail.com"
          healthcheck: "https://fierce-scrubland-23190.herokuapp.com/health"
          checkstring: "ok!"
          delay: 5
          rollbackonhealthcheckfailed: true
      - name: Bump verion and push tag
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch