name: Hello World!

on: 
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say Hello
        run: |
          echo "Hello World"
  date_job:
    runs-on: ubuntu-18.04
      steps:
        - name: Now it is
          run: |
            date
  content_job:
    runs-on: ubuntu-18.04
      steps:
        - name: Diretory Content
          run: |
            ls -l